name: docker-latest

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '0 14 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set docker name
        run: |
          DOCKER_NAME=$(echo ${{ github.repository }} | sed 's/docker\-//')
          echo "DOCKER_NAME=$DOCKER_NAME" >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_NAME }}:latest
